FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@11.9.0 --activate

WORKDIR /app

COPY . .

RUN pnpm install
RUN pnpm --filter api exec prisma generate

CMD ["pnpm", "--filter", "api", "test"]
